---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    name: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                operator: In
                values:
                  - Rohith
...