---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app
  labels:
    name: postgres-app
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    matchLabels:
      name: postgres-app
...