---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
  tolerations:
    - key: slave1
      value: Rohith
      operator: Equal
      effect: NoSchedule
...